name: expense
networks:
  expense:
volumes:
  mysql:
services:
  mysql:
    image: docksterharsha/mysql:1.0
    networks:
      - expense
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql 
  backend:
    image: docksterharsha/backend:1.0
    networks:
      - expense
    container_name: backend
    command: ['sh', '-c', 'sleep 20 && node /opt/server/index.js']
    depends_on:
      - mysql
  frontend:
    image: docksterharsha/frontend:1.0
    networks:
      - expense
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
