name: expense
networks:
  expense:
    driver: bridge
volumes:
  mysql:
    external: true
services:
  db:
    image: mysql:1.0
    environment:
      - MYSQL_ROOT_PASSWORD='ExpenseApp@1'
      - MYSQL_DATABASE='transactions' 
      - MYSQL_USER='expense' 
      - MYSQL_PASSWORD='ExpenseApp@1'
    networks:
      - expense
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql 
  backend:
    image: backend:1.0
    networks:
      - expense
    container_name: backend
    command: sh -c "sleep 20 && node /opt/server/index.js"
    depends_on:
      - mysql
  frontend:
    image: frontend:1.0
    networks:
      - expense
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"